apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
  namespace: demo
spec:
  chart:
    spec:
      chart: ./helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kbot
  interval: 1m0s
  values:
    image:
      repository: ghcr.io/vmahilevskyi/mastering-k8s-kbot-src
      tag: 1.2.0 # {"$imagepolicy": "flux-system:kbot-policy:tag"}
